language: node_js
node_js: "node"
git:
  depth: 3
before_script:
  - npm install chai
  - npm install -g mocha
  - npm install codacy-coverage --save
  - npm install -g istanbul
  - npm install --save fake-dom
  - npm install filereader
  - ln -s scripts src
script:
  - istanbul cover _mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | codacy-coverage
  - istanbul check-coverage --statement 100 --branch 100 --function 100 --lines 100
